config/routes.rb
My15five::Application.routes.draw do
  resources :projects

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  resources :reports do
    collection do
      get :current
      get :archive
    end
  end
  resources :answers

  root :to => 'pages#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
      can :access, :rails_admin
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :report
  belongs_to :question

  validates :body, :question_id, presence: true
  validates_associated :report

  scope :weekly, ->(user) {
    joins(:report).
    where(reports: {week_date: DateTools.current_friday})
    # todo: implement users filter by company
  }
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users

  validates :name, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope { order(:position) }

  has_many :answers

  validates :subject, :position, presence: true
end

app/models/report.rb
class Report < ActiveRecord::Base
  scope :sorted, -> { order(week_date: :desc) }
  scope :latest, -> { sorted.limit(1) }

  belongs_to :user
  has_many :answers

  validates :user_id, :week_date, presence: true

  accepts_nested_attributes_for :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w{manager user admin}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reports
  belongs_to :company

  validates :role, presence: true

  scope :managers, -> { where(role: 'manager') }

  def admin?
    role == 'admin'
  end

  def manager?
    role == 'manager'
  end

  def find_or_build_current_report
    current = reports.latest.first
    friday = DateTools.current_friday
    if current && current.week_date == friday
      current
    else
      current = reports.new(week_date: friday)
      Question.all.each do |q|
        current.answers.new(question_id: q.id)
      end
      current
    end
  end

  def self.send_weekly_reports
    User.managers.find_each do |u|
      ReportsMailer.weekly_report_email(u).deliver
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to current_reports_path if user_signed_in?
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    # set manager role by default
    resource.role = "manager"

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_resource, only: [:show, :update]

  def current
    @report = current_user.find_or_build_current_report
  end

  def archive
    @reports = current_user.reports.sorted
  end

  def create
    @report = Report.new(report_params)
    @report.week_date = DateTools.current_friday
    @report.user = current_user
    @report.save
  end

  def update
    @report.update_attributes(report_params)
  end

  private

  def report_params
    params.require(:report).permit(answers_attributes:
      [:question_id, :body, :id])
  end

  def set_resource
    @report = current_user.reports.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user, options = {})
    if user
      size = options[:size] || 42
      mode = options[:mode] || :wavatar # :mm, :identicon, :monsterid, :wavatar, :retro
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png?d=#{mode}&s=#{size}"
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "15five"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=root_path) 15five

          - if user_signed_in?
            .container.nav-collapse
              = render_navigation
              = render partial: 'shared/user_menu'

    .container
      .row
        .span12
          = bootstrap_flash
          = yield

      %footer

    = javascript_include_tag "application"

app/views/pages/home.html.haml
.well
  %h1 Welcome!

  = link_to "Sign up", new_user_registration_path, class: "btn btn-primary"
  = link_to "Sign in", new_user_session_path, class: "btn"

app/views/reports/_report.js.erb
<% if @report.errors.blank? %>
  $.gritter.add({
    title: 'Notice',
    text: 'Report successfully saved.',
  });
<% else %>
  $.gritter.add({
    title: 'Error',
    text: 'Errors occured while saving report.',
  });
<% end %>

app/views/reports/archive.html.haml
%h1 Past Reports

%table.table
  %tr
    %th Due
    %th
  - @reports.each do |report|
    %tr
      %td= l(report.week_date, format: :long)
      %td= link_to "Show", report_path(report), class: "btn"

app/views/reports/create.js.erb
<%= render partial: 'report' %>

app/views/reports/current.html.haml
%h1 Weekly Report

%p
  Due:
  = l(@report.week_date, format: :long)

%h2 Questions

= form_for @report, remote: true do |f|
  %ul
    = f.fields_for :answers do |answer_form|
      %li
        %h4= answer_form.object.question.subject
        = answer_form.hidden_field :question_id
        = answer_form.text_field :body

  = f.submit class: "btn btn-primary"

app/views/reports/show.html.haml
%h1 Report

%p
  Due:
  = l(@report.week_date, format: :long)

%h2 Questions

%ul
  - @report.answers.each do |answer|
    %li
      %h4= answer.question.subject
      = answer.body

app/views/reports/update.js.erb
<%= render partial: 'report' %>

app/views/shared/_user_menu.html.haml
%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
        = image_tag avatar_url(current_user, size: 22)
        = current_user.email
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to edit_user_registration_path do
            = glyph "user"
            My profile
        - if current_user.manager?
          %li
            = link_to "#" do
              = glyph "home"
              Manage Company

        %li.divider
        %li
          = link_to destroy_session_path(:user), method: :delete do
            = glyph "off"
            Log out